### ISSUE TITLE
dolphin@22.08.3-1722: download via aria2 failed

### ISSUE THREAD

**Issue by areen-c** [joaoricarte/jr-bucket#2]
Download: Status Legend:
Download: (ERR):error occurred.
Download: aria2 will resume download if the transfer is restarted.
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.

ERROR Download failed! (Error 22) HTTP response header was bad or unexpected
ERROR https://binary-factory.kde.org/view/Windows%2064-bit/job/Dolphin_Release_win64/1722/artifact/dolphin-22.08.3-1722-windows-msvc2019_64-cl.7z
    referer=https://binary-factory.kde.org/view/Windows%2064-bit/job/Dolphin_Release_win64/1722/artifact/
    dir=C:\Users\ariku\scoop\cache
    out=dolphin#22.08.3-1722#https_binary-factory.kde.org_view_Windows_2064-bit_job_Dolphin_Release_win64_1722_artifact_dolphin-22.08.3-1722-windows-msvc2019_64-cl.7z

ERROR & 'C:\Users\ariku\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\ariku\scoop\cache\dolphin.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.3 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=7008 --continue --summary-interval=0 --auto-save-interval=1

The correct link should like below, looks like the pattern changed.
https://binary-factory.kde.org/job/Dolphin_Release_win64/lastSuccessfulBuild/artifact/dolphin-22.08.3-1722-windows-cl-msvc2019-x86_64.7z

yours: dolphin-22.08.3-1722-windows-msvc2019_64-cl.7z
actual: dolphin-22.08.3-1722-windows-cl-msvc2019-x86_64.7z

**Comment by joaoricarte** [comment]
Dear Areen-c,
Thank you for your bug report! I corrected the .json bucket file. I think
all KDE SW in my bucket is now being updated correctly. I'm sorry for any
problem caused.

Best regards,
João Ricarte

**Comment by areen-c** [comment]
Hi, João Ricarte

Thanks for fixing it.
